---
abstract: 'note name and pitch number utility roles'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Music-PitchNum
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://github.com/thrig/Music-PitchNum.git
version: '0.04'
